### ISSUE TITLE
MySQL 버전 8로 변경

### ISSUE THREAD

**Issue by kunggom** [ZZinBros/miniprojects-2019#110]
현재 코드에서는 MySQL 버전 5를 쓰고 있는데, 제약조건 부여와 관련한 문제가 있다고 합니다. 버전 8에서는 이런 문제가 없다고 하는데, 이에 따라 서버의 MySQL 버전을 8로 바꾸었습니다. 따라서, 코드상의 DB dialect 또한 버전 8로 통일하는 것이 좋을 것 같습니다.

**Comment by andole87** [comment]
제약조건과 관련한 문제는 engie=innodb로 해결할 수 있습니다.
MySQL8Dialect는 "user" 가 예약어로 설정되어 있어 오류가 있을 수 있습니다.
