### ISSUE TITLE
application.yml 파일의 indent를 4칸으로 늘리는 게 좋을 것 같습니다.

### ISSUE THREAD

**Issue by kunggom** [ZZinBros/miniprojects-2019#143]
`application.yml`에서 logging 설정이 이상하게 안 먹혀서 한참 동안 고생했는데, 알고 보니 indent의 문제로 해당 설정 프로퍼티가 계속 엉뚱한 곳 아래에 들어가고 있었습니다. 현재 해당 파일의 indent는 2 Space인데, 구분을 좀 더 확실하게 하기 위해 4 Space로 바꾸는 것이 어떨까 합니다.

**Comment by andole87** [comment]
yaml은 인덴트에 관대합니다. 2space든 4space든 제대로 파싱되는 것은 맞습니다.
[참고](https://www.tutorialspoint.com/yaml/yaml_indentation_and_separation.htm)

가독성이 이슈라면 합의가 필요하겠네요.
