### ISSUE TITLE
로그인 오류

### ISSUE THREAD

**Issue by seonghun127** [ZZinBros/miniprojects-2019#223]
<img width="565" alt="스크린샷 2019-08-30 오후 4 31 04" src="https://user-images.githubusercontent.com/30451129/64001830-9b48d600-cb43-11e9-8f0a-26d4b37fbe1e.png">

로그인 오류 시 알림이 위와같이 나타납니다

**Comment by Deocksoo** [comment]
앗 감사합니다 수정할게요~
