### ISSUE TITLE
나의 타임라인에서 글을 쓸 때

### ISSUE THREAD

**Issue by seonghun127** [ZZinBros/miniprojects-2019#225]
<img width="1071" alt="스크린샷 2019-08-30 오후 4 36 03" src="https://user-images.githubusercontent.com/30451129/64002139-4fe2f780-cb44-11e9-8ff8-7477d9140d56.png">

사진없이 글만 있는 게시글을 작성하는 경우 위와같이 게시글이 두 개씩 생깁니다

**Comment by Deocksoo** [comment]
헉 마지막 커밋에서 오류가 생긴거같네요.. 수정하겠습니다!
