### ISSUE TITLE
댓글을 서버에서 보내주는 방식 결정

### ISSUE THREAD

**Issue by kunggom** [ZZinBros/miniprojects-2019#46]
댓글 기능 작성중에 이걸 서버에서 어떻게 클라이언트로 보내줘야 할지 구조가 명확하게 결정되지 않았다는 것을 깨달았습니다.
댓글에 별도의 컨트롤러가 필요할까요? 아니면 그냥 게시글(Post)에서 댓글 서비스만 가져다 쓰게 해야 할까요?
만약에 댓글은 별도 API를 통해 ajax 통신으로 가져오게 한다면 별도의 컨트롤러가 필요하겠지만, 그렇지 않다면 그냥 게시글에서 댓글의 서비스 레이어를 통해서 댓글을 가져오게 하는 것이 좋지 않은가 싶어서, 이를 결정해야 한다고 봅니다. 그래서 의견을 듣고 싶습니다. 지금까지 작성한 코드를 풀 리퀘 날립니다.

**Comment by yuyu154** [comment]
1. 말씀대로 처음 페이지를 표시할 때는 PostController에서 Post와 같이 보내는 것이 좋을 것 같아요.
2. 그리고 최초 표시 이후에 댓글을 추가할 때는 CommentController에서 AJAX를 써야될 것 같아요.

**Comment by Deocksoo** [comment]
저는 ajax 통신으로 댓글이 작성되도록 하고, 컨트롤러를 벌도로 만들어도 좋을거같아요! 그렇지 않으면 댓글을 작성할 때마다 새로고침이 될텐데, 그러면 불편하지 않을까요?

**Comment by Deocksoo** [comment]
저는 ajax 통신으로 댓글이 작성되도록 하고, 컨트롤러를 벌도로 만들어도 좋을거같아요. 댓글 작성이나 수정 기능을 곧 추가하게 되지 않을까 싶어서요!

**Comment by gch01410** [comment]
저도 러너덕 의견이랑 같습니다!
